on:
  pull_request:
  push:
    branches: [main]
    tags: ["v*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: Build

env:
  region: eu-west-2

permissions:
  id-token: write # For OIDC authentication with AWS
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint

    steps:
      - uses: actions/checkout@v6

      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: cargo fmt --check
        run: cargo fmt --check

      - name: cargo-semver-checks
        uses: obi1kenobi/cargo-semver-checks-action@v2
        continue-on-error: true

  clippy:
    runs-on: ubuntu-latest
    name: Clippy (${{ matrix.toolchain }})
    needs: [lint]

    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, beta]

    steps:
      - uses: actions/checkout@v6

      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy

      - name: cargo clippy
        run: cargo clippy

  msrv:
    runs-on: ubuntu-latest
    name: MSRV (${{ matrix.msrv }})
    needs: [lint]

    strategy:
      matrix:
        msrv: ["1.81.0"]

    steps:
      - uses: actions/checkout@v6

      - name: Install ${{ matrix.msrv }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.msrv }}

      - name: cargo +${{ matrix.msrv }} check
        run: cargo check

  docs:
    runs-on: ubuntu-latest
    name: Docs (nightly)
    needs: [lint]
    steps:
      - uses: actions/checkout@v6

      - name: Install nightly
        uses: dtolnay/rust-toolchain@nightly

      - name: Install Cargo Docs-rs
        run: cargo install cargo-docs-rs

      - name: Install Cargo Rdme
        run: cargo install cargo-rdme

      - name: cargo rdme --check
        run: cargo rdme --check

      - name: Build docs
        run: cargo docs-rs

      - name: cargo doc
        run: cargo doc --no-deps --all-features
        env:
          RUSTDOCFLAGS: --cfg docsrs

  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    needs: [clippy, msrv, docs]
    outputs:
      user_pool_id: ${{ steps.outputs.outputs.user_pool_id }}
      test_user_pool_client_id: ${{ steps.outputs.outputs.user_pool_client_id }}
    steps:
      - uses: actions/checkout@v6

      - uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: ${{ env.region }}
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}

      - uses: hashicorp/setup-terraform@v3

      - name: Initialise Terraform
        working-directory: ./infrastructure/tests
        run: |
          terraform init -input=false \
            -backend-config="bucket=hive-client-terraform-state" \
            -backend-config="key=ci/${{ github.run_id }}/terraform.tfstate" \
            -backend-config="region=${{ env.region }}" \
            -backend-config="use_lockfile=true"

      - name: Run format
        working-directory: ./infrastructure/tests
        run: terraform fmt -check -no-color

      - name: Run validate
        working-directory: ./infrastructure/tests
        run: terraform validate -no-color

      - name: Run apply
        working-directory: ./infrastructure/tests
        run: |
          terraform apply -input=false -auto-approve -no-color \
            -var="integration_test_user_email=${{ secrets.MOCK_USER_EMAIL }}" \
            -var="integration_test_user_password=${{ secrets.MOCK_USER_PASSWORD }}" \
            -var="aws_region=${{ env.region }}"

      - id: outputs
        name: Set outputs
        working-directory: ./infrastructure/tests
        run: |
          echo "user_pool_id=$(terraform output -raw test_user_pool_id)" >> $GITHUB_OUTPUT
          echo "user_pool_client_id=$(terraform output -raw test_user_pool_client_id)" >> $GITHUB_OUTPUT

  test:
    name: Tests (${{ matrix.os }} / ${{ matrix.toolchain }})
    runs-on: ${{ matrix.os }}
    needs: [setup]

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolchain: [stable, beta]

    steps:
      - uses: actions/checkout@v6

      - uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: ${{ env.region }}
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}

      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Mask outputs
        run: |
          # Mask all of the outputs in the workflow logs - its not _that_ sensitive as the user pool
          # is temporary, but its still a good idea to mask it
          echo "::add-mask::${{ needs.setup.outputs.test_user_pool_client_id }}"

      - name: Setup environment variables
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_POOL_ID: ${{ needs.setup.outputs.user_pool_id }}
          envkey_REGION: ${{ env.region }}
          envkey_CLIENT_ID: ${{ needs.setup.outputs.test_user_pool_client_id }}
          envkey_MOCK_USER_EMAIL: ${{ secrets.MOCK_USER_EMAIL }}
          envkey_MOCK_USER_PASSWORD: ${{ secrets.MOCK_USER_PASSWORD }}
          envkey_LIVE_USER_EMAIL: ${{ secrets.LIVE_USER_EMAIL }}
          envkey_LIVE_USER_PASSWORD: ${{ secrets.LIVE_USER_PASSWORD }}
          envkey_LIVE_TRUSTED_DEVICE_PASSWORD: ${{ secrets.LIVE_TRUSTED_DEVICE_PASSWORD }}
          envkey_LIVE_TRUSTED_DEVICE_KEY: ${{ secrets.LIVE_TRUSTED_DEVICE_KEY }}
          envkey_LIVE_TRUSTED_DEVICE_GROUP_KEY: ${{ secrets.LIVE_TRUSTED_DEVICE_GROUP_KEY }}
          directory: ./
          file_name: .env
          fail_on_empty: false

      - name: cargo test --locked
        run: cargo test --locked --all-features --all-targets

      - name: cargo test --doc
        run: cargo test --locked --all-features --doc

  minimal:
    runs-on: ubuntu-latest
    name: Test (minimal versions)
    needs: [setup]
    steps:
      - uses: actions/checkout@v6

      - uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: ${{ env.region }}
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}

      - name: Install stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install nightly for -Zminimal-versions
        uses: dtolnay/rust-toolchain@nightly

      - name: Mask outputs
        run: |
          # Mask all of the outputs in the workflow logs - its not _that_ sensitive as the user pool
          # is temporary, but its still a good idea to mask it
          echo "::add-mask::${{ needs.setup.outputs.test_user_pool_client_id }}"

      - name: Setup environment variables
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_POOL_ID: ${{ needs.setup.outputs.user_pool_id }}
          envkey_REGION: ${{ env.region }}
          envkey_CLIENT_ID: ${{ needs.setup.outputs.test_user_pool_client_id }}
          envkey_MOCK_USER_EMAIL: ${{ secrets.MOCK_USER_EMAIL }}
          envkey_MOCK_USER_PASSWORD: ${{ secrets.MOCK_USER_PASSWORD }}
          envkey_LIVE_USER_EMAIL: ${{ secrets.LIVE_USER_EMAIL }}
          envkey_LIVE_USER_PASSWORD: ${{ secrets.LIVE_USER_PASSWORD }}
          envkey_LIVE_TRUSTED_DEVICE_PASSWORD: ${{ secrets.LIVE_TRUSTED_DEVICE_PASSWORD }}
          envkey_LIVE_TRUSTED_DEVICE_KEY: ${{ secrets.LIVE_TRUSTED_DEVICE_KEY }}
          envkey_LIVE_TRUSTED_DEVICE_GROUP_KEY: ${{ secrets.LIVE_TRUSTED_DEVICE_GROUP_KEY }}
          directory: ./
          file_name: .env
          fail_on_empty: false

      - run: rustup default stable

      - name: cargo update -Zdirect-minimal-versions
        run: cargo +nightly update -Zdirect-minimal-versions

      - name: cargo test
        run: cargo test --locked --all-features --all-targets

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v6

      - uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: ${{ env.region }}
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}

      - name: Install nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: llvm-tools-preview

      - name: cargo install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Setup environment variables
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_POOL_ID: ${{ needs.setup.outputs.user_pool_id }}
          envkey_REGION: ${{ env.region }}
          envkey_CLIENT_ID: ${{ needs.setup.outputs.test_user_pool_client_id }}
          envkey_MOCK_USER_EMAIL: ${{ secrets.MOCK_USER_EMAIL }}
          envkey_MOCK_USER_PASSWORD: ${{ secrets.MOCK_USER_PASSWORD }}
          envkey_LIVE_USER_EMAIL: ${{ secrets.LIVE_USER_EMAIL }}
          envkey_LIVE_USER_PASSWORD: ${{ secrets.LIVE_USER_PASSWORD }}
          envkey_LIVE_TRUSTED_DEVICE_PASSWORD: ${{ secrets.LIVE_TRUSTED_DEVICE_PASSWORD }}
          envkey_LIVE_TRUSTED_DEVICE_KEY: ${{ secrets.LIVE_TRUSTED_DEVICE_KEY }}
          envkey_LIVE_TRUSTED_DEVICE_GROUP_KEY: ${{ secrets.LIVE_TRUSTED_DEVICE_GROUP_KEY }}
          file_name: .env
          fail_on_empty: false

      - run: cargo +nightly llvm-cov --locked --all-features --lcov --output-path lcov_unit.info

      - run: cargo +nightly llvm-cov --locked --doc --all-features --lcov --output-path lcov_docs.info

      - uses: actions/upload-artifact@v5
        with:
          name: coverage
          path: lcov_*.info

      - uses: coverage-robot/action@v1.0.10
        with:
          token: ${{ secrets.COVERAGE_TOKEN }}
          files: |
            lcov_unit.info
          tag: unit-tests
        continue-on-error: true

      - uses: coverage-robot/action@v1.0.10
        with:
          token: ${{ secrets.COVERAGE_TOKEN }}
          files: |
            lcov_docs.info
          tag: doc-tests
        continue-on-error: true

  teardown:
    name: Teardown Environment
    runs-on: ubuntu-latest
    needs: [setup, test, minimal, coverage]
    if: always() && needs.setup.result != 'skipped'
    steps:
      - uses: actions/checkout@v6

      - uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: ${{ env.region }}
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}

      - uses: hashicorp/setup-terraform@v3

      - name: Initialise Terraform
        working-directory: ./infrastructure/tests
        run: |
          terraform init -input=false \
            -backend-config="bucket=hive-client-terraform-state" \
            -backend-config="key=ci/${{ github.run_id }}/terraform.tfstate" \
            -backend-config="region=${{ env.region }}" \
            -backend-config="use_lockfile=true"

      - name: Run destroy
        working-directory: ./infrastructure/tests
        run: |
          terraform destroy -input=false -auto-approve -no-color \
            -var="integration_test_user_email=${{ secrets.MOCK_USER_EMAIL }}" \
            -var="integration_test_user_password=${{ secrets.MOCK_USER_PASSWORD }}" \
            -var="aws_region=${{ env.region }}"

  publish:
    name: Publish Crate
    needs: [test, coverage]
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install stable
        uses: dtolnay/rust-toolchain@stable

      - name: Login to crates.io
        run: cargo login ${{ secrets.CRATES_IO_API_TOKEN }}

      - name: Install cargo-release
        run: cargo install cargo-release

      - name: Publish version
        run: cargo release ${GITHUB_REF#refs/tags/v} -vv --no-tag --no-push --allow-branch HEAD --execute --no-confirm
